name: Predict
# This workflow is triggered on a schedule and manually

on:    
  workflow_dispatch: # Manually trigger the workflow

  schedule:
    - cron: '0 6 * * *'  # Runs at 6am UTC (9am EAT)

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # For repo access
      models: read  # Crucial for GitHub Models/Packages
    steps:
      # checkout the repository content to github runner
      - name: checkout repo content
        uses: actions/checkout@v2 

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Predict Ai
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
            DB_HOST: ${{ secrets.DB_HOST }} 
            DB_PORT: ${{ secrets.DB_PORT }} 
            DB_NAME: ${{ secrets.DB_NAME }} 
            DB_USER: ${{ secrets.DB_USER }} 
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }} 
        run: python predict_deep.py


